<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php
/** originnal
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<div class="nav-container">
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
</div>
<?php endif ?>
 */
?>
<div class="siteNavigation">
    <ul id="nav-customized">
		<?php
			/*CALL ADDITIONAL MENU FOR NAVIGATION*/
			if (Mage::getStoreConfig('cms/customization/additionalmenu'))
			{
				echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('cms/customization/additionalmenu'))->toHtml();
			}
			/*CALL DEFAULT NAVIGATION MENU*/
			$_menu = $this->renderCategoriesMenuHtml(0,'level-top');
			if ($_menu)
			{
				echo $_menu;
			}
		?>
    </ul>
</div>
<script type="text/javascript">
/*ENABLE MENU HIGHLIGHTING*/
document.observe("dom:loaded", function() {
	navObjs = $('nav-customized').children;
	for (var i=0; i<navObjs.length; i++)
	{
		/*console.log(navObjs[i]);*/
		aElement = navObjs[i].down('a');
		if (aElement.readAttribute('href').indexOf(document.URL) >= 0 && aElement.readAttribute('href').length <= document.URL.length )
		{
			aElement.parentElement.addClassName('active');
		}
		else
		{
			if (aElement.parentElement.hasClassName('active'));
			{
				aElement.parentElement.removeClassName('active');
			}
		}
	}
});
</script>
