<?php /* Smarty version 2.6.18, created on 2012-05-29 04:01:14
         compiled from coupons_panel.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'localize', 'coupons_panel.tpl', 4, false),)), $this); ?>
<!--    coupons_panel    -->

<fieldset>
    <legend><?php echo smarty_function_localize(array('str' => 'Create coupons'), $this);?>
</legend>
    <?php echo smarty_function_localize(array('str' => 'If you want to use coupon codes generated by your e-shop use [Import coupons]'), $this);?>
<br/>
    <?php echo smarty_function_localize(array('str' => 'If you want'), $this);?>
 <?php echo $this->_tpl_vars['PAP']; ?>
 <?php echo smarty_function_localize(array('str' => 'to generate coupon codes use [Generate coupons]'), $this);?>
<br/>
    <br/>
    <?php echo smarty_function_localize(array('str' => 'Both options will allow you to operate with the coupons. The only difference is that in second option you will need to setup your shop to accept codes generated by'), $this);?>
 <?php echo $this->_tpl_vars['PAP']; ?>
.<br/>
    <br/>
    <?php echo "<div id=\"importCoupons\"></div>"; ?>
    <?php echo "<div id=\"generateCoupons\"></div>"; ?>
</fieldset>

<?php echo "<div id=\"filter\"></div>"; ?>
<?php echo "<div id=\"grid\"></div>"; ?>