<!--    coupons_panel    -->

<fieldset>
    <legend>##Create coupons##</legend>
    ##If you want to use coupon codes generated by your e-shop use [Import coupons]##<br/>
    ##If you want## {$PAP} ##to generate coupon codes use [Generate coupons]##<br/>
    <br/>
    ##Both options will allow you to operate with the coupons. The only difference is that in second option you will need to setup your shop to accept codes generated by## {$PAP}.<br/>
    <br/>
    {widget id="importCoupons"}
    {widget id="generateCoupons"}
</fieldset>

{widget id="filter"}
{widget id="grid"}
