<?php
/**
 * View Program form
 */
?>
<?php $listPrograms = $this->getListProgram() ?>
<?php if (count($listPrograms)): ?>
<br/><br/>
<table class="data-table" id="list-program-table">
	<col width="1"/>
	<col width="1"/>
	<thead>
		<tr>
			<th colspan="3" height="40">
			<?php if (count($listPrograms) == 1): ?>
				<?php echo $this->__('OUR PROGRAM') ?>
			<?php else: ?>
				<?php echo $this->__('OUR PROGRAMS') ?>
			<?php endif ?>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php $i=0 ?>
		<?php foreach($listPrograms as $program): ?>
		<?php if($i>0): ?>
			<tr><td colspan="3" height="5">&nbsp;</td></tr>
		<?php endif; ?>
		<tr>
			<td rowspan="3" width="25%"><strong><?php echo $program->getName(); ?></strong></td>
			<td width="25%">
				<?php $commission = $program->getCommission() ? $program->getCommission() : 0 ?>
				<strong><?php echo $this->__('Commission Type') ?></strong>
			</td>
			<td width="50%">		
				<?php if($program->getCommissionType() == 'fixed'): ?>
					<?php echo $this->__('Pay-Per-Sale %s for each purchased item.',Mage::helper('core')->currency($commission)) ?>
				<?php else: ?> 
					<?php echo $this->__('Pay-Per-Sale %.2f %s for each sale you deliver.',$commission,'%') ?>
				<?php endif ?>			
			</td>
		</tr>
		<tr>
			<td>	
				<strong><?php echo $this->__('Payout Requirements') ?></strong>
			</td>
			<td>
				<?php echo $this->__('%s - Minimum balance required for payout.',Mage::helper('core')->currency($this->getMinPaymentRelease())) ?>
			</td>
		</tr>		 
		<tr>
			<td>	
				<strong><?php echo $this->__('Discount policy') ?></strong>
			</td>
			<td>
				<?php $discount = $program->getDiscount() ? $program->getDiscount() : 0 ?>
				<?php if($program->getDiscountType() == 'fixed'): ?>
					<?php echo $this->__('Discount %s for each purchased item.',Mage::helper('core')->currency($discount)) ?>
				<?php else: ?>
					<?php echo $this->__('Discount %.2f %s for each purchased item.',$discount,'%') ?>
				<?php endif	?>					
			</td>
		</tr>
		<?php $i++ ?>
	<?php endforeach; ?>
	</tbody>
</table>
<div class="clear">&nbsp;</div>
<?php endif ?>