<?php
	/**
	 * Payment method onepage checkout template 
	 */
?>
<dl class="sp-methods" id="checkout-payment-method-load">

<?php $customerrewardEnabled = $this->customerrewardEnabled() ?>
<?php if ($customerrewardEnabled): ?>
	<dt>
		<input type="checkbox" name="payment[use_point]" id="use_point" checked="checked" onclick="usePointCheck();" />
		<label for="use_point"><?php echo $this->__('Use my point(s) balance') ?></label>
	</dt>
	<dt>
		<input type="text" name="payment[point_amount]" id="point_amount" onchange="pointAmountChange();" />
		<label for="point_amount"><?php echo $this->__('of %s point(s) %s available.',$this->getBalance(),$this->getMoneyBalance()) ?></label>
	</dt>
<?php endif //end ?>

<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
<?php if ($customerrewardEnabled): ?>
	var usePointCheck = function (){
		$('point_amount').disabled = !$('use_point').checked;
	}
	var maxPointsForOrder = <?php echo $this->getMaxPointsForOrder() ?>;
	$('point_amount').value = maxPointsForOrder;
	var pointAmountChange = function(){
		if (isNaN($('point_amount').value) || $('point_amount').value < 0 ) $('point_amount').value = 0;
		if ($('point_amount').value > maxPointsForOrder) $('point_amount').value = maxPointsForOrder;
	}
	$('use_point').disabled = false;
	usePointCheck();
<?php endif ?>
//]]>
</script>