<?php
/**
 * @see Mage_Checkout_Block_Cart_Shipping
 */
?>
<div class="shipping">
	<div class="border-left-center">
		<div class="border-right-center">
			<div class="border-top-center">
				<div class="border-bot-center">
					<div class="left-top-center">
						<div class="right-top-center">
							<div class="left-bot-center">
								<div class="right-bot-center">
									<div class="indent-center">    
<h4><?php echo $this->__('Estimate Shipping and Tax') ?></h4>
<form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-zip-form">
        <fieldset>
            <p><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
            <ul class="form-list">
                <li>
                    <label for="country"><?php echo $this->__('Country') ?></label><br />
                    <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>
                </li>
            <?php //if($this->getStateActive()): ?>
                <li>
                    <label for="region_id"><?php echo $this->__('State/Province') ?><?php if ($this->isStateProvinceRequired()):?> <span class="required">*</span><?php endif;?></label><br />
                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;"<?php echo ($this->isStateProvinceRequired() ? ' class="validate-select"' : '') ?>>
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                   <script type="text/javascript">
                   //<![CDATA[
                       $('region_id').setAttribute('defaultValue',  "<?php echo $this->getEstimateRegionId() ?>");
                   //]]>
                   </script>
                   <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getEstimateRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                </li>
            <?php //endif; ?>
            <?php if($this->getCityActive()): ?>
                <li>
                    <label for="city"><?php echo $this->__('City') ?><?php if ($this->isCityRequired()):?> <span class="required">*</span><?php endif;?></label><br />
                    <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
                </li>
            <?php endif; ?>
                <li>
                    <label for="postcode"><?php echo $this->__('Zip/Postal Code') ?><?php if ($this->isZipCodeRequired()):?> <span class="required">*</span><?php endif;?></label><br />
                    <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
                </li>
            </ul>
            <div class="buttons-set">
                <button type="button" onclick="coShippingMethodForm.submit()" class="button"><span><span><span><?php echo $this->__('Get a Quote') ?></span></span></span></button>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    //]]>
    </script>
	
<?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
<form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>">
    <fieldset>
        <dl class="sp-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt style="width:180px"><?php echo $this->getCarrierName($code) ?></dt>
                <dd>
                    <ul>
                    <?php foreach ($_rates as $_rate): ?>
                        <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>>
                           <?php if ($_rate->getErrorMessage()): ?>
                                <?php echo $_rate->getErrorMessage() ?>
                           <?php else: ?>
                                <input name="estimate_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
                                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </label>
                           <?php endif ?>
						<?php if($code == 'storepickup') : ?>
								<div id="free-location-box" >
									<?php echo $this->getChildHtml('storepickup') ?>
								</div>
						<?php endif ?>						   
                        </li>
                    <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
        <div class="buttons-set">
            <button type="submit" class="button" name="do" value="<?php echo $this->__('Update Total') ?>"><span><span><span><?php echo $this->__('Update Total') ?></span></span></span></button>
        </div>
    </fieldset>
</form>
<?php endif; ?>	

<script type="text/javascript">
//<![CDATA[
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
    Validation.addAllThese(
    [
           ['validate-postcode', '<?php echo $this->__('Please enter a valid zip code. For example 90602 or 90602-1234.') ?>', function(v) {
                var element = $('postcode');
                if (element && ('' != element.value)) {
                    if (!element.value.match(/(^[A-z0-9]{2,10}([\s]{0,2}|[\-]{0,2})[A-z0-9]{2,10}$)/ )) {
                        return false;
                    }
                }
                return true;
           }]
    ]
    );
//]]>
</script>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<script type="text/javascript">
if(document.getElementById('free-location-box'))

	document.getElementById('free-location-box').style.display='none';

setEventForRave();

function setEventForRave()
	{
		var element;
		
		var allItems = document.getElementsByName('estimate_method');

		for(var i = 0; i < allItems.length; i++)
		{
			element = allItems[i];
			
			if(element.type == "radio")
			{	
				if(isRaveMethod(element.id))
				{
					 Event.observe(element.id, 'click', function(event){ 
						if(document.getElementById('free-location-box'))		
							document.getElementById('free-location-box').style.display='block';
					});

					if(element.checked == true){
						if(document.getElementById('free-location-box'))
							document.getElementById('free-location-box').style.display='block';
					}
					
				
				} else {
					 Event.observe(element.id, 'click', function(event){ 
						if(document.getElementById('free-location-box'))		
							document.getElementById('free-location-box').style.display='none';
					});	
					
					if(element.checked == true){
						if(document.getElementById('free-location-box'))
							document.getElementById('free-location-box').style.display='none';
					}
				}
			}
		}		
	}

	function isRaveMethod(idRatio)
	{

		var i = (idRatio+'').indexOf("storepickup");
		
		return i === -1 ? false : true;
	}	
</script>