
<?php $stores = $this->getStoreByLocation(); ?>
<?php $size = $this->getMapSize();?>
<br>
<div id="map" style="width: <?php echo $size[0];?>px; height: <?php echo $size[1];?>px"></div>
<div class="input-box storepickup-box">
	<input type="hidden" name="store_id" id="store_id" value="" class="required-entry" />
	<div class="clear" ></div>					
</div>
<script type="text/javascript">
//<![CDATA[
//var map = new GMap(document.getElementById("map"));
	//map.addControl(new GLargeMapControl3D()); // added
	//map.addControl(new GMapTypeControl()); // added
//var latlngbounds = new GLatLngBounds();
var myLatlng = new google.maps.LatLng(-34.397, 150.644);
var myOptions = {
zoom: 8,
center: myLatlng,
mapTypeId: google.maps.MapTypeId.ROADMAP
}
map = new google.maps.Map(document.getElementById("map"),myOptions);
var bounds = new google.maps.LatLngBounds();
<?php 
	foreach($stores as $store) {
		$store=$store['info'];
		$coordinates['lat'] = $store->getStoreLatitude();
		$coordinates['lng'] = $store->getStoreLongitude();
		if($coordinates['lat'] == '0.000' && $coordinates['lat'] == '0.000')
			$coordinates = $this->getCoordinates();
		//$address = $store->getFormatedAddress();	
		$address = $store->getFormatedAddressforMap();
?>
var setLat = <?php echo $coordinates['lat'] ?>;
var setLon = <?php echo $coordinates['lng'] ?>; 
var storeId = <?php echo $store->getId(); ?>;
var store_info = '<?php echo Mage::helper('storepickup')->jsQuoteEscape($store->getStoreName()) ?><br/><?php echo str_replace("\n","",str_replace("\r","",Mage::helper('storepickup')->jsQuoteEscape($address))); ?><br/>Distance : <?php echo $store->getDistance()?> (m)' ;
marker_point = new google.maps.LatLng(setLat, setLon);
bounds.extend(marker_point);
var infoWindow = new google.maps.InfoWindow();
placeMarker(setLat,setLon,store_info,storeId);
<?php }?>

map.fitBounds(bounds);	
map.setCenter(bounds.getCenter());

function placeMarker(setLat, setLon,store_info,storeId) {
	var message = "geotagged geo:lat=" + setLat + " geo:lon=" + setLon + " "; 
	var messageRoboGEO = setLat + ";" + setLon + ""; 
	
	var point = new google.maps.LatLng(setLat, setLon);
	var marker = new google.maps.Marker({
		  position: point,
		  map: map
		});
	
	<?php if(count($stores) ==1) { ?>
		//map.centerAndZoom(point, 2);
	<?php } ?>
		google.maps.event.addListener(marker, 'click', function(event) {
			infoWindow.setContent(store_info);
			infoWindow.setPosition(event.latLng);
			infoWindow.open(map);
			$('store_id').value = storeId;
			changestorebyMap();
		});
}
<?php if(count($stores) > 1) { ?>
	//map.setCenter( latlngbounds.getCenter( ), map.getBoundsZoomLevel( latlngbounds ) );
<?php } ?>

function changestorebyMap()
{
	if ($('shipping_date'))
			$('shipping_date').value ='';
		
		var storeId;
		
		storeId = $('store_id').value;
		
		var url = '<?php echo $this->getUrl('storepickup/index/changestore'); ?>' ;
		
		url = url + 'store_id/' + storeId;
	   
		var request = new Ajax.Request(url,{method: 'get', onFailure: ""}); 
		
		if($('storepickup-box') != null)
			$('storepickup-box').style.display = 'block';
		if($('date-box') != null)
			$('date-box').style.display = 'block';
		if($('time-box') != null)	
			$('time-box').style.display = 'block';
			
			//end all store mode
		if($('curr-store') != null)
		{
			var curr_store_id = $('curr-store').value;
			
			if($('store-info-'+ curr_store_id) != null)
			{
				$('store-info-'+ curr_store_id).style.display = 'none';
			}		
			
			if($('store-info-'+ storeId) != null)
			{
				$('store-info-'+ storeId).style.display = 'block';
				$('curr-store').value = storeId;
			}		
		}
}
//]]>
</script>  

<a href="<?php echo $this->getUrl('storepickup/index/index')?>" target="_blank"><?php echo $this->__('View list of all stores')?></a>

<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar-win2k-1.css"  /> 
<script type="text/javascript">var Translator = new Translate([]);</script> 
<script type="text/javascript">
//<![CDATA[
enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
Calendar._am = "AM"; // am/pm
Calendar._pm = "PM";
 
// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "About the calendar";
 
Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" +
"Date selection:\n" +
"- Use the \xab, \xbb buttons to select year\n" +
"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
"- Hold mouse button on any of the above buttons for faster selection.";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"Time selection:\n" +
"- Click on any of the time parts to increase it\n" +
"- or Shift-click to decrease it\n" +
"- or click and drag for faster selection.";
 
Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
Calendar._TT["GO_TODAY"] = "Go Today";
Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
Calendar._TT["SEL_DATE"] = "Select date";
Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';
 
// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "Display %s first";
 
// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";
 
Calendar._TT["CLOSE"] = "Close";
Calendar._TT["TODAY"] = "Today";
Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";
 
// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";
 
Calendar._TT["WK"] = "Week";
Calendar._TT["TIME"] = "Time:";
 
CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;

//]]>
</script>
<?php if(count($stores)):?>
<?php $modelshipping = Mage::getModel('storepickup/shipping_storepickup') ?>
<?php $early_date_nonce = $modelshipping->getConfigData('early_date_nonce') ?>
<?php $store_not_found_nonce = $modelshipping->getConfigData('store_not_found_nonce') ?>
<div>	
	<input type="hidden" name="early_date_nonce" id="early_date_nonce" value="<?php echo $early_date_nonce ?>">
	<input type="hidden" name="store_not_found_nonce" id="store_not_found_nonce" value="<?php echo $store_not_found_nonce ?>">
	<div id="select-store" >
			
		<?php 
			$storeID = Mage::app()->getStore()->getId();
			if (Mage::getStoreConfig('carriers/storepickup/display_timedate') == 1) {
		?>	
		<div class="input-box storepickup-box">
			<label for="date"><?php echo $this->__('Shipping Date') ?> </label>
			<input  name="shipping_date" id="shipping_date" value="" class="required-entry input-text " onchange="changeDate('<?php echo Mage::helper('storepickup')->getChangDateUrl(); ?>');"/>
			<img src="<?php echo Mage::getBaseUrl('skin')?>/adminhtml/default/default/images/grid-cal.gif" alt="dateinput" class="v-middle" id="shipping_date_trig" title="dateinput"  />
		</div>
		<div id="date-notation"></div>
		<div class="input-box storepickup-box">
			<label for="date"><?php echo $this->__('Shipping Time') ?> </label>				
			<select id="shipping_time" name="shipping_time" class="required-entry validate-select">
				<option value="" selected><?php echo $this->__('Shipping Time') ?></option>
			</select>
			<span id="time-please-wait" style="display:none;" class="opc-please-wait">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading Shipping Times...') ?>
			</span>							
		</div>
		<?php } ?>
	</div>
	<div id="store-info">
	<?php if(count($stores)): ?>
		<?php foreach($stores as $store) : ?>
		<?php $store=$store['info']?>
		<?php $address = $store->getFormatedAddress();?>
		<div id="store-info-<?php echo $store->getId()?>" style="display:none;" >
			<div class="st_info left">
				<span class="title store-address"><?php echo $store->getStoreName() ?></span>
				<span class="store-address"><?php echo $address."<br/>Distance : ".$store->getDistance()." (m)" ?></span>
				<?php if($store->getDescription() !=null) { ?>
				<div>
					<span class="title store-address"><?php echo $this->__('Description') ?></span>
					<span class="store-address"><?php echo $store->getDescription() ?></span>
				</div>
				<?php } ?>
			</div>
		</div>
		<?php endforeach;?>
	<?php endif;?>
	<input type="hidden" id="curr-store" value="" />
	</div>
</div>
	<div class="clear fix">&nbsp;</div>
	
<?php else :?>
	<?php echo $this->__('Not found stores')?>
<?php endif;?>		


<script type="text/javascript">
	//<![CDATA[
		var storepickup = new Storepickup('<?php echo Mage::helper('storepickup')->getChangeStoreUrl(); ?>');

		//$('s_method_storepickup_storepickup').checked = true;
		
		if($('shipping_time')) {
		
			Event.observe('shipping_time', 'change', function(event){ 		
					storepickup.changeTime('<?php echo Mage::helper('storepickup')->getChangTimeUrl(); ?>');
			});	}
		if($('shipping_date_trig')) {

			Event.observe('shipping_date_trig', 'click', function(event){ 		
					$('shipping_time').selectedIndex = 0;
			}); 

		Calendar.setup({
					inputField: "shipping_date",
					ifFormat: "%m-%d-%Y",
					showsTime: false,
					button: "shipping_date_trig",
					//align: "bl",
					singleClick : true
		});}
	//]]>
	</script>
