
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>calendar/calendar-win2k-1.css"  /> 
<script type="text/javascript">var Translator = new Translate([]);</script> 
<script type="text/javascript">
//<![CDATA[
enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
Calendar._am = "AM"; // am/pm
Calendar._pm = "PM";
 
// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "About the calendar";
 
Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" +
"Date selection:\n" +
"- Use the \xab, \xbb buttons to select year\n" +
"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
"- Hold mouse button on any of the above buttons for faster selection.";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"Time selection:\n" +
"- Click on any of the time parts to increase it\n" +
"- or Shift-click to decrease it\n" +
"- or click and drag for faster selection.";
 
Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
Calendar._TT["GO_TODAY"] = "Go Today";
Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
Calendar._TT["SEL_DATE"] = "Select date";
Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';
 
// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "Display %s first";
 
// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";
 
Calendar._TT["CLOSE"] = "Close";
Calendar._TT["TODAY"] = "Today";
Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";
 
// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";
 
Calendar._TT["WK"] = "Week";
Calendar._TT["TIME"] = "Time:";
 
CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;

//]]>
</script>
<?php $listStore = $this->getStoreByLocation() ;
?>
<?php if(count($listStore)) :?>
	<?php $modelshipping = Mage::getModel('storepickup/shipping_storepickup') ?>
	<?php $style = $modelshipping->getConfigData('css') ?>
	<?php $early_date_nonce = $modelshipping->getConfigData('early_date_nonce') ?>
	<?php $store_not_found_nonce = $modelshipping->getConfigData('store_not_found_nonce') ?>
	<input type="hidden" name="early_date_nonce" id="early_date_nonce" value="<?php echo $early_date_nonce ?>">
	<input type="hidden" name="store_not_found_nonce" id="store_not_found_nonce" value="<?php echo $store_not_found_nonce ?>">
	<div id="select-store" >
		<div class="input-box storepickup-box">
			<label for="date"><?php echo $this->__('Stores') ?> <span class="required">*</span></label>				
			<select name="store_id" id="store_id" class="required-entry validate-select" >
				<option value="" selected ><?php echo $this->__('Select Store') ?></option>
				<?php foreach($listStore as $store): ?>
					<option value="<?php echo $store->getId() ?>" ><?php echo $store->getStoreName() ?></option>
				<?php endforeach;?>
			</select>
			<div class="clear" ></div>					
		</div>		
		<div class="input-box storepickup-box">
			<label for="date"><?php echo $this->__('Shipping Date') ?> </label>
			<input  name="shipping_date" id="shipping_date" value="" class="required-entry " onchange="changeDate('<?php echo Mage::helper('storepickup')->getChangDateUrl(); ?>');"/>
			<img src="<?php echo Mage::getBaseUrl('skin')?>/adminhtml/default/default/images/grid-cal.gif" alt="dateinput" class="v-middle" id="shipping_date_trig" title="dateinput"  />
		</div><div id="date-notation"></div>
		<div class="clear" ></div>
		<div class="input-box storepickup-box">
			<label for="date"><?php echo $this->__('Shipping Time') ?> </label>				
			<select id="shipping_time" name="shipping_time" class="required-entry validate-select">
				<option value="" selected><?php echo $this->__('Shipping Time') ?></option>
			</select>
			<span id="time-please-wait" style="display:none;" class="opc-please-wait">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading Shipping Times...') ?>
			</span>							
		</div>
	</div>
	<div id="store-info">
	<?php if(count($listStore)): ?>
		<?php foreach($listStore as $store) : ?>
		<?php $address = $store->getAddress().'<br/>'. $store->getCity() ?>
		<?php $address .='<br/>'. $store->getRegion() .', '. $store->getZipcode() .'<br/>'. $store->getCountryName()?>
			<div id="store-info-<?php echo $store->getId()?>" style="display:none;" >
				<span class="title"><?php echo $store->getStoreName() ?></span>
				<span class="store-address"><?php echo $address ?></span>
			</div>
		<?php endforeach;?>
	<?php endif;?>
	<input type="hidden" id="curr-store" value="" />
	</div>
	<div class="clear fix">&nbsp;</div>
	<script type="text/javascript">
	//<![CDATA[
		var storepickup = new Storepickup('<?php echo Mage::helper('storepickup')->getChangeStoreUrl(); ?>');

		$('s_method_storepickup_storepickup').checked = true;
		
		Event.observe('store_id', 'change', function(event){ 
				storepickup.changeStore();
		});
		
		Event.observe('shipping_time', 'change', function(event){ 		
				storepickup.changeTime('<?php echo Mage::helper('storepickup')->getChangTimeUrl(); ?>');
		});	

		Event.observe('shipping_date_trig', 'click', function(event){ 		
				$('shipping_time').selectedIndex = 0;
		});

		Calendar.setup({
					inputField: "shipping_date",
					ifFormat: "%m-%d-%Y",
					showsTime: false,
					button: "shipping_date_trig",
					align: "Bl",
					singleClick : true
		});
	//]]>
	</script>
	<style text="css">
	<?php echo $style ?>
	</style>	
<?php else :?>
	<?php echo $this->__('Not found stores')?>
<?php endif; ?>