<?php if ($this->isPossibleOnepageCheckout()):?>
<div class="tobasket">
	<a>
		<button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
			<span>
				<span>
					<?php echo $this->__('Proceed to Checkout') ?>
				</span>
			</span>
		</button>
	</a>
</div>
<?php endif?>

